# Generated by Django 5.1.1 on 2024-09-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMasterX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_identifier', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
                ('temp_fahrenheit', models.FloatField()),
                ('humidity_percent', models.FloatField()),
                ('pressure_hpa', models.FloatField()),
                ('uv_index', models.IntegerField()),
                ('rain_mm', models.FloatField()),
                ('operational_status', models.CharField(max_length=20)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['city_name', 'recorded_at'], name='weather_mas_city_na_2f3df3_idx')],
            },
        ),
    ]
