# Generated by Django 5.1.1 on 2024-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_master_x', '0004_alter_weathermasterx_humidity_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermasterx',
            name='pressure_hpa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
