# Generated by Django 5.1.1 on 2024-09-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['content_type', 'object_id'], name='stations_st_content_5d6485_idx'),
        ),
    ]
