# Generated by Django 5.1.1 on 2024-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stations', '0002_station_stations_st_content_5d6485_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['city'], name='stations_st_city_f1c409_idx'),
        ),
    ]
