# Generated by Django 5.1.1 on 2024-09-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulgarianMeteoProData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('temperature_celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_speed_kph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('station_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['city', 'timestamp'], name='bulgarian_m_city_4a8380_idx')],
            },
        ),
    ]
