# Generated by Django 5.1.1 on 2024-09-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulgarian_meteo_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulgarianmeteoprodata',
            name='raw_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
