# Generated by Django 5.1.1 on 2024-09-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulgarian_meteo_pro', '0002_bulgarianmeteoprodata_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulgarianmeteoprodata',
            name='station_status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], max_length=20),
        ),
    ]
