# Generated by Django 5.1.1 on 2024-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulgarian_meteo_pro', '0003_alter_bulgarianmeteoprodata_station_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulgarianmeteoprodata',
            name='station_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20),
        ),
    ]
